# Generated by Django 2.2.7 on 2019-11-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.PositiveSmallIntegerField()),
                ('colorid', models.PositiveSmallIntegerField()),
                ('sizeid', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('isdelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.UserInfo')),
            ],
            options={
                'unique_together': {('goodsid', 'colorid', 'sizeid')},
            },
        ),
    ]
